In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    453     64   John
1  2023-01-02       B   West    581     84   Mary
2  2023-01-03       C  North    573     59    Bob
3  2023-01-04       D  South    434     84  Alice
4  2023-01-05       A   East    588     63   John
5  2023-01-06       B   West    187     10   Mary
6  2023-01-07       C  North    634     29    Bob
7  2023-01-08       D  South    484     70  Alice
8  2023-01-09       A   East    291     46   John
9  2023-01-10       B   West    155     77   Mary
10 2023-01-11       C  North    141     35    Bob
11 2023-01-12       D  South    593     71  Alice
12 2023-01-13       A   East    817     10   John
13 2023-01-14       B   West    191     95   Mary
14 2023-01-15       C  North    115     14    Bob
15 2023-01-16       D  South    189     86  Alice
16 2023-01-17       A   East    528     53   John
17 2023-01-18       B   West    993     19   Mary
18 2023-01-19       C  North    615     50    Bob
19 2023-01-20       D  South    808     74  Alice

In [5]:
pd.pivot_table(df, values="Sales", index='Region', columns='Product')

Product      A      B      C      D
Region
East     535.4    NaN    NaN    NaN
North      NaN    NaN  415.6    NaN
South      NaN    NaN    NaN  501.6
West       NaN  421.4    NaN    NaN

In [8]:
pivot2 =pd.pivot_table(df, values=["Sales", 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     535.4    NaN    NaN    NaN  47.2   NaN   NaN   NaN
North      NaN    NaN  415.6    NaN   NaN   NaN  37.4   NaN
South      NaN    NaN    NaN  501.6   NaN   NaN   NaN  77.0
West       NaN  421.4    NaN    NaN   NaN  57.0   NaN   NaN

In [10]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0